# Generated by Django 4.2.1 on 2023-06-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dir',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dirname', models.CharField(max_length=150)),
                ('project', models.CharField(max_length=150)),
                ('owner', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.CharField(max_length=150)),
                ('directory', models.CharField(max_length=150)),
                ('project', models.CharField(max_length=150)),
                ('owner', models.CharField(max_length=150)),
                ('public', models.CharField(max_length=1)),
                ('private', models.CharField(max_length=1)),
                ('cnt', models.IntegerField()),
                ('department', models.CharField(max_length=150)),
                ('isDelete', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='HistoryAction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project', models.CharField(max_length=150)),
                ('directory', models.CharField(max_length=150)),
                ('file', models.CharField(max_length=150)),
                ('fileid', models.IntegerField()),
                ('username', models.CharField(max_length=150)),
                ('action', models.CharField(max_length=150)),
                ('modify_date', models.DateTimeField(auto_now_add=True)),
                ('version', models.IntegerField()),
                ('isFile', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('projectname', models.CharField(max_length=150)),
                ('department', models.CharField(max_length=150)),
                ('owner', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=1500)),
            ],
        ),
    ]
