# Generated by Django 4.2.1 on 2023-05-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dir',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dirname', models.CharField(max_length=150)),
                ('project', models.CharField(max_length=150)),
                ('owner', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'dir',
                'verbose_name_plural': 'dirs',
                'db_table': 'directory',
            },
        ),
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.CharField(max_length=150)),
                ('directory', models.CharField(max_length=150)),
                ('project', models.CharField(max_length=150)),
                ('owner', models.CharField(max_length=150)),
                ('public', models.CharField(max_length=1)),
                ('private', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name': 'doc',
                'verbose_name_plural': 'docs',
                'db_table': 'document',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('projectname', models.CharField(max_length=150)),
                ('department', models.CharField(max_length=150)),
                ('owner', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
                'db_table': 'project',
            },
        ),
    ]
