# Generated by Django 4.2.1 on 2023-06-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyaction',
            name='directory',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='historyaction',
            name='file',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='historyaction',
            name='fileid',
            field=models.IntegerField(null=True),
        ),
    ]
