# Generated by Django 4.2.1 on 2023-06-04 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dir',
            options={},
        ),
        migrations.AlterModelOptions(
            name='doc',
            options={},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.AlterModelTable(
            name='dir',
            table=None,
        ),
        migrations.AlterModelTable(
            name='doc',
            table=None,
        ),
        migrations.AlterModelTable(
            name='project',
            table=None,
        ),
    ]
