# Generated by Django 4.2.1 on 2023-06-04 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentmanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryAction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project', models.CharField(max_length=150)),
                ('directory', models.CharField(max_length=150)),
                ('file', models.CharField(max_length=150)),
                ('username', models.CharField(max_length=150)),
                ('action', models.CharField(max_length=150)),
                ('modify_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
