# Generated by Django 4.2.1 on 2023-06-02 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documentmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dir',
            name='dirname',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='dir',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dir',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dir',
            name='project',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterUniqueTogether(
            name='dir',
            unique_together={('dirname', 'project')},
        ),
    ]
